// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meetup.proto

package yuan.storm.proto;

public final class MeetupProtos {
  private MeetupProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MeetupEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:yuan.storm.MeetupEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required uint64 time = 2;</code>
     */
    boolean hasTime();
    /**
     * <code>required uint64 time = 2;</code>
     */
    long getTime();

    /**
     * <code>optional string category = 3;</code>
     */
    boolean hasCategory();
    /**
     * <code>optional string category = 3;</code>
     */
    java.lang.String getCategory();
    /**
     * <code>optional string category = 3;</code>
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>optional string event_url = 4;</code>
     */
    boolean hasEventUrl();
    /**
     * <code>optional string event_url = 4;</code>
     */
    java.lang.String getEventUrl();
    /**
     * <code>optional string event_url = 4;</code>
     */
    com.google.protobuf.ByteString
        getEventUrlBytes();

    /**
     * <code>optional string name = 5;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 rsvp_count = 6;</code>
     */
    boolean hasRsvpCount();
    /**
     * <code>optional int32 rsvp_count = 6;</code>
     */
    int getRsvpCount();

    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    boolean hasVenue();
    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    yuan.storm.proto.MeetupProtos.MeetupEvent.Venue getVenue();
    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder getVenueOrBuilder();
  }
  /**
   * Protobuf type {@code yuan.storm.MeetupEvent}
   */
  public static final class MeetupEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:yuan.storm.MeetupEvent)
      MeetupEventOrBuilder {
    // Use MeetupEvent.newBuilder() to construct.
    private MeetupEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MeetupEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MeetupEvent defaultInstance;
    public static MeetupEvent getDefaultInstance() {
      return defaultInstance;
    }

    public MeetupEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MeetupEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readUInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              category_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              eventUrl_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              name_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              rsvpCount_ = input.readInt32();
              break;
            }
            case 58: {
              yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = venue_.toBuilder();
              }
              venue_ = input.readMessage(yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(venue_);
                venue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              yuan.storm.proto.MeetupProtos.MeetupEvent.class, yuan.storm.proto.MeetupProtos.MeetupEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<MeetupEvent> PARSER =
        new com.google.protobuf.AbstractParser<MeetupEvent>() {
      public MeetupEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MeetupEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MeetupEvent> getParserForType() {
      return PARSER;
    }

    public interface VenueOrBuilder extends
        // @@protoc_insertion_point(interface_extends:yuan.storm.MeetupEvent.Venue)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string address = 1;</code>
       */
      boolean hasAddress();
      /**
       * <code>optional string address = 1;</code>
       */
      java.lang.String getAddress();
      /**
       * <code>optional string address = 1;</code>
       */
      com.google.protobuf.ByteString
          getAddressBytes();

      /**
       * <code>optional string city = 2;</code>
       */
      boolean hasCity();
      /**
       * <code>optional string city = 2;</code>
       */
      java.lang.String getCity();
      /**
       * <code>optional string city = 2;</code>
       */
      com.google.protobuf.ByteString
          getCityBytes();

      /**
       * <code>optional string state = 3;</code>
       */
      boolean hasState();
      /**
       * <code>optional string state = 3;</code>
       */
      java.lang.String getState();
      /**
       * <code>optional string state = 3;</code>
       */
      com.google.protobuf.ByteString
          getStateBytes();

      /**
       * <code>optional string country = 4;</code>
       */
      boolean hasCountry();
      /**
       * <code>optional string country = 4;</code>
       */
      java.lang.String getCountry();
      /**
       * <code>optional string country = 4;</code>
       */
      com.google.protobuf.ByteString
          getCountryBytes();

      /**
       * <code>optional double latitude = 5;</code>
       */
      boolean hasLatitude();
      /**
       * <code>optional double latitude = 5;</code>
       */
      double getLatitude();

      /**
       * <code>optional double longitude = 6;</code>
       */
      boolean hasLongitude();
      /**
       * <code>optional double longitude = 6;</code>
       */
      double getLongitude();
    }
    /**
     * Protobuf type {@code yuan.storm.MeetupEvent.Venue}
     */
    public static final class Venue extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:yuan.storm.MeetupEvent.Venue)
        VenueOrBuilder {
      // Use Venue.newBuilder() to construct.
      private Venue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Venue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Venue defaultInstance;
      public static Venue getDefaultInstance() {
        return defaultInstance;
      }

      public Venue getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Venue(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                address_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                city_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                state_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                country_ = bs;
                break;
              }
              case 41: {
                bitField0_ |= 0x00000010;
                latitude_ = input.readDouble();
                break;
              }
              case 49: {
                bitField0_ |= 0x00000020;
                longitude_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_Venue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_Venue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.class, yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder.class);
      }

      public static com.google.protobuf.Parser<Venue> PARSER =
          new com.google.protobuf.AbstractParser<Venue>() {
        public Venue parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Venue(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Venue> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ADDRESS_FIELD_NUMBER = 1;
      private java.lang.Object address_;
      /**
       * <code>optional string address = 1;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            address_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CITY_FIELD_NUMBER = 2;
      private java.lang.Object city_;
      /**
       * <code>optional string city = 2;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            city_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string city = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATE_FIELD_NUMBER = 3;
      private java.lang.Object state_;
      /**
       * <code>optional string state = 3;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            state_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string state = 3;</code>
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int COUNTRY_FIELD_NUMBER = 4;
      private java.lang.Object country_;
      /**
       * <code>optional string country = 4;</code>
       */
      public boolean hasCountry() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            country_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string country = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LATITUDE_FIELD_NUMBER = 5;
      private double latitude_;
      /**
       * <code>optional double latitude = 5;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double latitude = 5;</code>
       */
      public double getLatitude() {
        return latitude_;
      }

      public static final int LONGITUDE_FIELD_NUMBER = 6;
      private double longitude_;
      /**
       * <code>optional double longitude = 6;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional double longitude = 6;</code>
       */
      public double getLongitude() {
        return longitude_;
      }

      private void initFields() {
        address_ = "";
        city_ = "";
        state_ = "";
        country_ = "";
        latitude_ = 0D;
        longitude_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getAddressBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getCityBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getStateBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getCountryBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeDouble(5, latitude_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeDouble(6, longitude_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getAddressBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getCityBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getStateBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getCountryBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(5, latitude_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(6, longitude_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(yuan.storm.proto.MeetupProtos.MeetupEvent.Venue prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code yuan.storm.MeetupEvent.Venue}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:yuan.storm.MeetupEvent.Venue)
          yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_Venue_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_Venue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.class, yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder.class);
        }

        // Construct using yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          address_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          city_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          state_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          country_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          latitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000010);
          longitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_Venue_descriptor;
        }

        public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue getDefaultInstanceForType() {
          return yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance();
        }

        public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue build() {
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue buildPartial() {
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue result = new yuan.storm.proto.MeetupProtos.MeetupEvent.Venue(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.address_ = address_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.city_ = city_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.country_ = country_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.latitude_ = latitude_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.longitude_ = longitude_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof yuan.storm.proto.MeetupProtos.MeetupEvent.Venue) {
            return mergeFrom((yuan.storm.proto.MeetupProtos.MeetupEvent.Venue)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(yuan.storm.proto.MeetupProtos.MeetupEvent.Venue other) {
          if (other == yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance()) return this;
          if (other.hasAddress()) {
            bitField0_ |= 0x00000001;
            address_ = other.address_;
            onChanged();
          }
          if (other.hasCity()) {
            bitField0_ |= 0x00000002;
            city_ = other.city_;
            onChanged();
          }
          if (other.hasState()) {
            bitField0_ |= 0x00000004;
            state_ = other.state_;
            onChanged();
          }
          if (other.hasCountry()) {
            bitField0_ |= 0x00000008;
            country_ = other.country_;
            onChanged();
          }
          if (other.hasLatitude()) {
            setLatitude(other.getLatitude());
          }
          if (other.hasLongitude()) {
            setLongitude(other.getLongitude());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (yuan.storm.proto.MeetupProtos.MeetupEvent.Venue) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object address_ = "";
        /**
         * <code>optional string address = 1;</code>
         */
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public java.lang.String getAddress() {
          java.lang.Object ref = address_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              address_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAddressBytes() {
          java.lang.Object ref = address_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            address_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder setAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          address_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder clearAddress() {
          bitField0_ = (bitField0_ & ~0x00000001);
          address_ = getDefaultInstance().getAddress();
          onChanged();
          return this;
        }
        /**
         * <code>optional string address = 1;</code>
         */
        public Builder setAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          address_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object city_ = "";
        /**
         * <code>optional string city = 2;</code>
         */
        public boolean hasCity() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string city = 2;</code>
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              city_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string city = 2;</code>
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string city = 2;</code>
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 2;</code>
         */
        public Builder clearCity() {
          bitField0_ = (bitField0_ & ~0x00000002);
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>optional string city = 2;</code>
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          city_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object state_ = "";
        /**
         * <code>optional string state = 3;</code>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              state_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000004);
          state_ = getDefaultInstance().getState();
          onChanged();
          return this;
        }
        /**
         * <code>optional string state = 3;</code>
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          state_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object country_ = "";
        /**
         * <code>optional string country = 4;</code>
         */
        public boolean hasCountry() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string country = 4;</code>
         */
        public java.lang.String getCountry() {
          java.lang.Object ref = country_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              country_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string country = 4;</code>
         */
        public com.google.protobuf.ByteString
            getCountryBytes() {
          java.lang.Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string country = 4;</code>
         */
        public Builder setCountry(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          country_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string country = 4;</code>
         */
        public Builder clearCountry() {
          bitField0_ = (bitField0_ & ~0x00000008);
          country_ = getDefaultInstance().getCountry();
          onChanged();
          return this;
        }
        /**
         * <code>optional string country = 4;</code>
         */
        public Builder setCountryBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          country_ = value;
          onChanged();
          return this;
        }

        private double latitude_ ;
        /**
         * <code>optional double latitude = 5;</code>
         */
        public boolean hasLatitude() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional double latitude = 5;</code>
         */
        public double getLatitude() {
          return latitude_;
        }
        /**
         * <code>optional double latitude = 5;</code>
         */
        public Builder setLatitude(double value) {
          bitField0_ |= 0x00000010;
          latitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double latitude = 5;</code>
         */
        public Builder clearLatitude() {
          bitField0_ = (bitField0_ & ~0x00000010);
          latitude_ = 0D;
          onChanged();
          return this;
        }

        private double longitude_ ;
        /**
         * <code>optional double longitude = 6;</code>
         */
        public boolean hasLongitude() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional double longitude = 6;</code>
         */
        public double getLongitude() {
          return longitude_;
        }
        /**
         * <code>optional double longitude = 6;</code>
         */
        public Builder setLongitude(double value) {
          bitField0_ |= 0x00000020;
          longitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double longitude = 6;</code>
         */
        public Builder clearLongitude() {
          bitField0_ = (bitField0_ & ~0x00000020);
          longitude_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:yuan.storm.MeetupEvent.Venue)
      }

      static {
        defaultInstance = new Venue(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:yuan.storm.MeetupEvent.Venue)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>required uint64 time = 2;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 time = 2;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int CATEGORY_FIELD_NUMBER = 3;
    private java.lang.Object category_;
    /**
     * <code>optional string category = 3;</code>
     */
    public boolean hasCategory() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string category = 3;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          category_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string category = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_URL_FIELD_NUMBER = 4;
    private java.lang.Object eventUrl_;
    /**
     * <code>optional string event_url = 4;</code>
     */
    public boolean hasEventUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string event_url = 4;</code>
     */
    public java.lang.String getEventUrl() {
      java.lang.Object ref = eventUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          eventUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string event_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEventUrlBytes() {
      java.lang.Object ref = eventUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 5;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RSVP_COUNT_FIELD_NUMBER = 6;
    private int rsvpCount_;
    /**
     * <code>optional int32 rsvp_count = 6;</code>
     */
    public boolean hasRsvpCount() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 rsvp_count = 6;</code>
     */
    public int getRsvpCount() {
      return rsvpCount_;
    }

    public static final int VENUE_FIELD_NUMBER = 7;
    private yuan.storm.proto.MeetupProtos.MeetupEvent.Venue venue_;
    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    public boolean hasVenue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue getVenue() {
      return venue_;
    }
    /**
     * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
     */
    public yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder getVenueOrBuilder() {
      return venue_;
    }

    private void initFields() {
      id_ = "";
      time_ = 0L;
      category_ = "";
      eventUrl_ = "";
      name_ = "";
      rsvpCount_ = 0;
      venue_ = yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getEventUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, rsvpCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, venue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCategoryBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getEventUrlBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, rsvpCount_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, venue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static yuan.storm.proto.MeetupProtos.MeetupEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(yuan.storm.proto.MeetupProtos.MeetupEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code yuan.storm.MeetupEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:yuan.storm.MeetupEvent)
        yuan.storm.proto.MeetupProtos.MeetupEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                yuan.storm.proto.MeetupProtos.MeetupEvent.class, yuan.storm.proto.MeetupProtos.MeetupEvent.Builder.class);
      }

      // Construct using yuan.storm.proto.MeetupProtos.MeetupEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVenueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        category_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        eventUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        rsvpCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (venueBuilder_ == null) {
          venue_ = yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance();
        } else {
          venueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return yuan.storm.proto.MeetupProtos.internal_static_yuan_storm_MeetupEvent_descriptor;
      }

      public yuan.storm.proto.MeetupProtos.MeetupEvent getDefaultInstanceForType() {
        return yuan.storm.proto.MeetupProtos.MeetupEvent.getDefaultInstance();
      }

      public yuan.storm.proto.MeetupProtos.MeetupEvent build() {
        yuan.storm.proto.MeetupProtos.MeetupEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public yuan.storm.proto.MeetupProtos.MeetupEvent buildPartial() {
        yuan.storm.proto.MeetupProtos.MeetupEvent result = new yuan.storm.proto.MeetupProtos.MeetupEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.category_ = category_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.eventUrl_ = eventUrl_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.rsvpCount_ = rsvpCount_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (venueBuilder_ == null) {
          result.venue_ = venue_;
        } else {
          result.venue_ = venueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof yuan.storm.proto.MeetupProtos.MeetupEvent) {
          return mergeFrom((yuan.storm.proto.MeetupProtos.MeetupEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(yuan.storm.proto.MeetupProtos.MeetupEvent other) {
        if (other == yuan.storm.proto.MeetupProtos.MeetupEvent.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasCategory()) {
          bitField0_ |= 0x00000004;
          category_ = other.category_;
          onChanged();
        }
        if (other.hasEventUrl()) {
          bitField0_ |= 0x00000008;
          eventUrl_ = other.eventUrl_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasRsvpCount()) {
          setRsvpCount(other.getRsvpCount());
        }
        if (other.hasVenue()) {
          mergeVenue(other.getVenue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        yuan.storm.proto.MeetupProtos.MeetupEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (yuan.storm.proto.MeetupProtos.MeetupEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>required uint64 time = 2;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 time = 2;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>optional string category = 3;</code>
       */
      public boolean hasCategory() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string category = 3;</code>
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            category_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string category = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string category = 3;</code>
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 3;</code>
       */
      public Builder clearCategory() {
        bitField0_ = (bitField0_ & ~0x00000004);
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string category = 3;</code>
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventUrl_ = "";
      /**
       * <code>optional string event_url = 4;</code>
       */
      public boolean hasEventUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string event_url = 4;</code>
       */
      public java.lang.String getEventUrl() {
        java.lang.Object ref = eventUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            eventUrl_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string event_url = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEventUrlBytes() {
        java.lang.Object ref = eventUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string event_url = 4;</code>
       */
      public Builder setEventUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        eventUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string event_url = 4;</code>
       */
      public Builder clearEventUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        eventUrl_ = getDefaultInstance().getEventUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string event_url = 4;</code>
       */
      public Builder setEventUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        eventUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 5;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      private int rsvpCount_ ;
      /**
       * <code>optional int32 rsvp_count = 6;</code>
       */
      public boolean hasRsvpCount() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 rsvp_count = 6;</code>
       */
      public int getRsvpCount() {
        return rsvpCount_;
      }
      /**
       * <code>optional int32 rsvp_count = 6;</code>
       */
      public Builder setRsvpCount(int value) {
        bitField0_ |= 0x00000020;
        rsvpCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rsvp_count = 6;</code>
       */
      public Builder clearRsvpCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        rsvpCount_ = 0;
        onChanged();
        return this;
      }

      private yuan.storm.proto.MeetupProtos.MeetupEvent.Venue venue_ = yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue, yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder, yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder> venueBuilder_;
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public boolean hasVenue() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue getVenue() {
        if (venueBuilder_ == null) {
          return venue_;
        } else {
          return venueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public Builder setVenue(yuan.storm.proto.MeetupProtos.MeetupEvent.Venue value) {
        if (venueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          venue_ = value;
          onChanged();
        } else {
          venueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public Builder setVenue(
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder builderForValue) {
        if (venueBuilder_ == null) {
          venue_ = builderForValue.build();
          onChanged();
        } else {
          venueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public Builder mergeVenue(yuan.storm.proto.MeetupProtos.MeetupEvent.Venue value) {
        if (venueBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              venue_ != yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance()) {
            venue_ =
              yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.newBuilder(venue_).mergeFrom(value).buildPartial();
          } else {
            venue_ = value;
          }
          onChanged();
        } else {
          venueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public Builder clearVenue() {
        if (venueBuilder_ == null) {
          venue_ = yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.getDefaultInstance();
          onChanged();
        } else {
          venueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder getVenueBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getVenueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      public yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder getVenueOrBuilder() {
        if (venueBuilder_ != null) {
          return venueBuilder_.getMessageOrBuilder();
        } else {
          return venue_;
        }
      }
      /**
       * <code>optional .yuan.storm.MeetupEvent.Venue venue = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          yuan.storm.proto.MeetupProtos.MeetupEvent.Venue, yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder, yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder> 
          getVenueFieldBuilder() {
        if (venueBuilder_ == null) {
          venueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              yuan.storm.proto.MeetupProtos.MeetupEvent.Venue, yuan.storm.proto.MeetupProtos.MeetupEvent.Venue.Builder, yuan.storm.proto.MeetupProtos.MeetupEvent.VenueOrBuilder>(
                  getVenue(),
                  getParentForChildren(),
                  isClean());
          venue_ = null;
        }
        return venueBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:yuan.storm.MeetupEvent)
    }

    static {
      defaultInstance = new MeetupEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:yuan.storm.MeetupEvent)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yuan_storm_MeetupEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yuan_storm_MeetupEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_yuan_storm_MeetupEvent_Venue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_yuan_storm_MeetupEvent_Venue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014meetup.proto\022\nyuan.storm\"\211\002\n\013MeetupEve" +
      "nt\022\n\n\002id\030\001 \002(\t\022\014\n\004time\030\002 \002(\004\022\020\n\010category" +
      "\030\003 \001(\t\022\021\n\tevent_url\030\004 \001(\t\022\014\n\004name\030\005 \001(\t\022" +
      "\022\n\nrsvp_count\030\006 \001(\005\022,\n\005venue\030\007 \001(\0132\035.yua" +
      "n.storm.MeetupEvent.Venue\032k\n\005Venue\022\017\n\007ad" +
      "dress\030\001 \001(\t\022\014\n\004city\030\002 \001(\t\022\r\n\005state\030\003 \001(\t" +
      "\022\017\n\007country\030\004 \001(\t\022\020\n\010latitude\030\005 \001(\001\022\021\n\tl" +
      "ongitude\030\006 \001(\001B \n\020yuan.storm.protoB\014Meet" +
      "upProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_yuan_storm_MeetupEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_yuan_storm_MeetupEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yuan_storm_MeetupEvent_descriptor,
        new java.lang.String[] { "Id", "Time", "Category", "EventUrl", "Name", "RsvpCount", "Venue", });
    internal_static_yuan_storm_MeetupEvent_Venue_descriptor =
      internal_static_yuan_storm_MeetupEvent_descriptor.getNestedTypes().get(0);
    internal_static_yuan_storm_MeetupEvent_Venue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_yuan_storm_MeetupEvent_Venue_descriptor,
        new java.lang.String[] { "Address", "City", "State", "Country", "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
